services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    volumes:
      - insPolDb:/var/opt/mssql
    environment:
      - SA_PASSWORD=pasSword123
      - ACCEPT_EULA="Y"
    ports:
      - 1434:1433
        
volumes:
  insPolDb: